### ISSUE TITLE
Error in Inkscape v1.0.1 (duplicated ?) 'NameError: name 'long' is not defined'

### ISSUE THREAD

**Issue by samuelortion** [FrankSAURET/Tableau#2]
I could not create a table using Tableau.

## System properties
* OS - windows 10
* Inkscape version : 1.0.1
* Tableau version : 1.0

### Here is the complete error message : 
```python
tableau.py:24: DeprecationWarning: inkex.localize was moved to inkex.localization.localize
  inkex.localize()
tableau.py:31: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:36: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:41: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:46: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:51: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:56: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:61: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:66: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:71: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
tableau.py:167: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
Traceback (most recent call last):
  File "tableau.py", line 167, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\deprecated.py", line 181, in affect
    return self.run(args=args)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "tableau.py", line 91, in effect
    Couleur = self.getColorString(self.options.Couleur)[0]
  File "tableau.py", line 83, in getColorString
    longColor = long(longColor)
NameError: name 'long' is not defined
```

I hope this could help for troubleshooting.

**Comment by FrankSAURET** [comment]
Hi,
I have update [this on inkscape repository](https://inkscape.org/~FrankI4466/%E2%98%85tableau) (inkscape.org > download > Extensions).
Frank
